name: CI
on:
- push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn re:build
    - run: yarn test
  android:
    name: Build android
    runs-on: ubuntu-20.04
    needs:
    - test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - run: yarn
    - run: yarn re:build
    - run: adb devices
    - run: npx react-native run-ios
  ios:
    name: Build ios
    needs:
    - test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - run: yarn
    - run: yarn re:build
    - run: npx react-native run-ios
