name: CI
on:
- push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn re:build
    - run: yarn test
  android:
    name: Build android
    needs:
    - test
    runs-on: ubuntu-20.04
    # env:
    #   JAVA_OPTS: "-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee"
      # AVDMANAGER_OPTS: "--add-modules java.se.ee"
    # SDKMANAGER_OPTS: "--add-modules java.se.ee"
      # DEFAULT_JVM_OPTS: '"-Dcom.android.sdklib.toolsdir=${APP_HOME}" -XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'
      # PATH: "${PATH}:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    # - run: ${ANDROID_HOME}/tools/android list target
    # - run: ${ANDROID_HOME}/platform-tools/adb devices
    - run: yarn
    - run: yarn re:build
    - run: curl -L -o adoptopenjdk-8.tar.gz 'https://api.adoptopenjdk.net/v3/binary/latest/8/ga/linux/x64/jdk/hotspot/normal/adoptopenjdk?project=jdk'
    - uses: actions/setup-java@v1
      with:
        java-version: 8
        architecture: x64
        jdkFile: ./adoptopenjdk-8.tar.gz
    # - run: cd android && gradle build && cd ..
    - run: echo y | sudo $ANDROID_HOME/tools/bin/sdkmanager --verbose "${{ matrix.emu-version }}"
    - run: sudo ${ANDROID_HOME}/tools/bin/avdmanager create avd -n test -k "system-images;android-29;google_apis;x86"
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - run: npx react-native run-android
  ios:
    name: Build ios
    needs:
    - test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - run: yarn
    - run: cd ios && pod install && cd ..
    - run: yarn re:build
    - run: npx react-native run-ios
