name: CI
on:
- push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn re:build
    - run: yarn test
  android:
    name: Build android
    needs:
    - test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "system-images;android-30;google_apis;x86"
    - run: ${ANDROID_HOME}/tools/android list targets
    - run: ${ANDROID_HOME}/platform-tools/adb devices
    - run: yarn
    - run: yarn re:build
    - run: npx react-native run-android
  ios:
    name: Build ios
    needs:
    - test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - run: yarn
    - run: cd ios && pod install && cd ..
    - run: yarn re:build
    - run: npx react-native run-ios
